//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.25 at 09:31:23 PM EET 
//


package preprod.qa.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the preprod.qa.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: preprod.qa.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SearchFreeTimeByDoctorResponse }
     * 
     */
    public SearchFreeTimeByDoctorResponse createSearchFreeTimeByDoctorResponse() {
        return new SearchFreeTimeByDoctorResponse();
    }

    /**
     * Create an instance of {@link Booking }
     * 
     */
    public Booking createBooking() {
        return new Booking();
    }

    /**
     * Create an instance of {@link AddBookingResponse }
     * 
     */
    public AddBookingResponse createAddBookingResponse() {
        return new AddBookingResponse();
    }

    /**
     * Create an instance of {@link CancelBookingRequest }
     * 
     */
    public CancelBookingRequest createCancelBookingRequest() {
        return new CancelBookingRequest();
    }

    /**
     * Create an instance of {@link AddBookingRequest }
     * 
     */
    public AddBookingRequest createAddBookingRequest() {
        return new AddBookingRequest();
    }

    /**
     * Create an instance of {@link SearchDoctorBySpecialRequest }
     * 
     */
    public SearchDoctorBySpecialRequest createSearchDoctorBySpecialRequest() {
        return new SearchDoctorBySpecialRequest();
    }

    /**
     * Create an instance of {@link SearchDoctorBySpecialResponse }
     * 
     */
    public SearchDoctorBySpecialResponse createSearchDoctorBySpecialResponse() {
        return new SearchDoctorBySpecialResponse();
    }

    /**
     * Create an instance of {@link Doctor }
     * 
     */
    public Doctor createDoctor() {
        return new Doctor();
    }

    /**
     * Create an instance of {@link CancelBookingResponse }
     * 
     */
    public CancelBookingResponse createCancelBookingResponse() {
        return new CancelBookingResponse();
    }

    /**
     * Create an instance of {@link SearchFreeTimeByDoctorRequest }
     * 
     */
    public SearchFreeTimeByDoctorRequest createSearchFreeTimeByDoctorRequest() {
        return new SearchFreeTimeByDoctorRequest();
    }

}
