//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.25 at 09:31:23 PM EET 
//


package preprod.qa.soap;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="timeSlotStart" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="timeSlotFinish" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="doctorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "timeSlotStart",
    "timeSlotFinish",
    "doctorName"
})
@XmlRootElement(name = "searchFreeTimeByDoctorRequest")
public class SearchFreeTimeByDoctorRequest {

    @XmlElement(required = true)
    protected BigInteger timeSlotStart;
    @XmlElement(required = true)
    protected BigInteger timeSlotFinish;
    @XmlElement(required = true)
    protected String doctorName;

    /**
     * Gets the value of the timeSlotStart property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTimeSlotStart() {
        return timeSlotStart;
    }

    /**
     * Sets the value of the timeSlotStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTimeSlotStart(BigInteger value) {
        this.timeSlotStart = value;
    }

    /**
     * Gets the value of the timeSlotFinish property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTimeSlotFinish() {
        return timeSlotFinish;
    }

    /**
     * Sets the value of the timeSlotFinish property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTimeSlotFinish(BigInteger value) {
        this.timeSlotFinish = value;
    }

    /**
     * Gets the value of the doctorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * Sets the value of the doctorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoctorName(String value) {
        this.doctorName = value;
    }

}
